global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'self'
    static_configs:
      - targets: ['192.168.254.220:9090']

  - job_name: 'rpi_node_exporter'
    static_configs:
      - targets: ['192.168.0.4:9100']

  - job_name: 'docker_cadvisor'
    static_configs:
      - targets: ['192.168.254.222:8080']

  - job_name: 'caddy'
    static_configs:
      - targets: ['192.168.254.3:2019']

  - job_name: 'website_and_http_checks'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://geeksbsmrt.com
        - https://smrtgeekdevs.com
        - https://pihole.smrtgeekdevs.com
        - http://192.168.254.1/admin/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.254.223:9115

  - job_name: 'dns_service_checks'
    metrics_path: /probe
    params:
      module: [dns_probe]
    static_configs:
      - targets:
        - '192.168.254.1:53'
        - '192.168.254.253:53'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.254.223:9115  # Blackbox Exporter's MacVlan IP:Port
