name: Dependabot Auto-Merge

on: pull_request

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: self-hosted
        if: github.repository == 'geeksbsmrt/RaspberryPi' && github.actor == 'dependabot[bot]'
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - name: Approve PR
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      await github.rest.pulls.createReview({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.issue.number,
                          event: 'APPROVE'
                      });

            - name: Enable auto-merge
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      await github.graphql(`
                          mutation($pullRequestId: ID!) {
                              enablePullRequestAutoMerge(input: {
                                  pullRequestId: $pullRequestId,
                                  mergeMethod: SQUASH
                              }) {
                                  clientMutationId
                              }
                          }
                      `, {
                          pullRequestId: context.payload.pull_request.node_id
                      });
