name: Deploy Docker Stack to Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify SOPS and age installation on runner
        run: |
          echo "Checking SOPS version..."
          sops --version --check-for-updates
          echo "Checking age version..."
          age --version

      - name: Decrypt secrets.sops.env to .env file on Pi
        env:
          SOPS_AGE_KEY: ${{ secrets.RUNNER_AGE_PRIVATE_KEY }}
          TARGET_ENV_FILE: ${{ secrets.DOCKER_DIR }}/.env
          # Using an intermediate env var for the target file path for clarity in the script
        run: |
          echo "Decrypting secrets from $GITHUB_WORKSPACE/secrets.sops.env to ${TARGET_ENV_FILE}"
          sudo -E sops --decrypt "$GITHUB_WORKSPACE/secrets.sops.env" > "${TARGET_ENV_FILE}"
          sudo -E chmod 600 "${TARGET_ENV_FILE}"
          echo ".env file created at ${TARGET_ENV_FILE} with restricted permissions."


      - name: Prepare Docker Configurations (Template Prometheus Config)
        env:
          DOCKER_CONFIG_SOURCE_DIR: "$GITHUB_WORKSPACE/docker"
          DOCKER_CONFIG_TARGET_DIR: "${{ secrets.DOCKER_DIR }}"
        run: |
          echo "Sourcing environment variables from ${DOCKER_CONFIG_TARGET_DIR}/.env"
          set -a # Automatically export all variables from sourced file
          source "${DOCKER_CONFIG_TARGET_DIR}/.env"
          set +a

          echo "Templating Prometheus configuration..."
          envsubst < "${DOCKER_CONFIG_SOURCE_DIR}/prometheus/config/prometheus.yml.template" > "${DOCKER_CONFIG_SOURCE_DIR}/prometheus/config/prometheus.yml"
          echo "Prometheus configuration templated."

      - name: Sync configuration files
        run: |
          echo "Syncing repository contents to ${{ secrets.DOCKER_DIR }}"
          rsync -av --checksum \
            "$GITHUB_WORKSPACE/docker/" \
            "${{ secrets.DOCKER_DIR }}/" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "*.sops.env"

      - name: Navigate to Docker Compose directory
        run: cd "${{ secrets.DOCKER_DIR }}"

      - name: Pull latest Docker images
        run: |
          cd "${{ secrets.DOCKER_DIR }}"
          sudo docker compose pull

      - name: Apply Docker Compose changes
        run: |
          cd "${{ secrets.DOCKER_DIR }}"
          sudo docker compose up -d --remove-orphans

      - name: (Optional) Prune unused Docker images
        if: success()
        run: |
          echo "Pruning unused Docker images..."
          sudo docker image prune -af
